name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Build the program
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          ls -a && git clone -b Lab2 --single-branch https://github.com/aneroid11/Labs_Progr_2sem && ls -a && cd Labs_Progr_2sem/2_2_6/
